export enum UserRole {
  CONSUMER = 'CONSUMER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum ConnectionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  ASSIGNED = 'ASSIGNED',
  UNDER_VERIFICATION = 'UNDER_VERIFICATION',
  DOCUMENTS_PENDING = 'DOCUMENTS_PENDING',
  VERIFICATION_COMPLETE = 'VERIFICATION_COMPLETE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CONNECTION_SCHEDULED = 'CONNECTION_SCHEDULED',
  CONNECTION_COMPLETED = 'CONNECTION_COMPLETED',
}

export enum ConnectionType {
  DOMESTIC = 'DOMESTIC',
  COMMERCIAL = 'COMMERCIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  AGRICULTURAL = 'AGRICULTURAL',
}

export enum DocumentType {
  AADHAAR_CARD = 'AADHAAR_CARD',
  PAN_CARD = 'PAN_CARD',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  OWNERSHIP_PROOF = 'OWNERSHIP_PROOF',
  PASSPORT_PHOTO = 'PASSPORT_PHOTO',
  AFFIDAVIT = 'AFFIDAVIT',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum NotificationType {
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
}

export enum NotificationStatus {
  SIMULATED = 'SIMULATED',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum ConsentType {
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  DPDP_DATA_COLLECTION = 'DPDP_DATA_COLLECTION',
  MARKETING_COMMUNICATIONS = 'MARKETING_COMMUNICATIONS',
}

export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  CONNECTION_APPLIED = 'CONNECTION_APPLIED',
  CONNECTION_STATUS_UPDATED = 'CONNECTION_STATUS_UPDATED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',
  ADMIN_USER_DEACTIVATED = 'ADMIN_USER_DEACTIVATED',
  ADMIN_USER_EDITED = 'ADMIN_USER_EDITED',
  // ── Workflow engine audit actions ──
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  APPLICATION_ASSIGNED = 'APPLICATION_ASSIGNED',
  APPLICATION_REASSIGNED = 'APPLICATION_REASSIGNED',
  WORKFLOW_TRANSITION = 'WORKFLOW_TRANSITION',
  VERIFICATION_STARTED = 'VERIFICATION_STARTED',
  VERIFICATION_COMPLETED = 'VERIFICATION_COMPLETED',
  REMARK_ADDED = 'REMARK_ADDED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  DOCUMENT_REQUESTED = 'DOCUMENT_REQUESTED',
  CONNECTION_SCHEDULED = 'CONNECTION_SCHEDULED',
  CONNECTION_COMPLETED = 'CONNECTION_COMPLETED',
}

/**
 * Workflow action identifiers — recorded in `application_timeline` and
 * `workflow_actions`. Covers application lifecycle actions plus document
 * review and remark events.
 */
export enum WorkflowActionType {
  APPLICATION_CREATED = 'APPLICATION_CREATED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  SUBMIT = 'SUBMIT',
  ASSIGN = 'ASSIGN',
  REASSIGN = 'REASSIGN',
  START_VERIFICATION = 'START_VERIFICATION',
  REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS',
  COMPLETE_VERIFICATION = 'COMPLETE_VERIFICATION',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  SCHEDULE_CONNECTION = 'SCHEDULE_CONNECTION',
  COMPLETE_CONNECTION = 'COMPLETE_CONNECTION',
  ADD_REMARK = 'ADD_REMARK',
  DOCUMENT_APPROVE = 'DOCUMENT_APPROVE',
  DOCUMENT_REJECT = 'DOCUMENT_REJECT',
  DOCUMENT_REQUEST = 'DOCUMENT_REQUEST',
}

/** Lifecycle of an application-assignment record. */
export enum AssignmentStatus {
  ACTIVE = 'ACTIVE',
  REPLACED = 'REPLACED',
  CLOSED = 'CLOSED',
}

/** Outcome of a single document verification action. */
export enum VerificationResult {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REQUESTED = 'REQUESTED',
}

export const WORKFLOW_ROLES = {
  CONSUMER: UserRole.CONSUMER,
  ADMIN: UserRole.ADMIN,
  SUPER_ADMIN: UserRole.SUPER_ADMIN,
} as const;

/** Terminal workflow states — no outgoing transitions. */
export const TERMINAL_WORKFLOW_STATES = [
  ConnectionStatus.REJECTED,
  ConnectionStatus.CONNECTION_COMPLETED,
] as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

export const JWT = {
  ACCESS_TOKEN_COOKIE: 'bses_access_token',
  REFRESH_TOKEN_COOKIE: 'bses_refresh_token',
} as const;
