import { describe, it, expect } from 'vitest';
import { detectFileType, validateUploadContent, MAX_DECODED_PIXELS } from '../../src/utils/file-safety';
import { ValidationError } from '@bses/shared';

// A genuine 1x1 PNG (base64).
const TINY_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
  'base64',
);
// A genuine tiny JPEG (base64).
const TINY_JPEG = Buffer.from(
  '/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigD//2Q==',
  'base64',
);
const TINY_PDF = Buffer.from('%PDF-1.4\n%%EOF');
// A genuine 1x1 WebP (generated by sharp).
const TINY_WEBP = Buffer.from(
  'UklGRlgAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAIAAAAAf1ZQOCAwAAAA0AEAnQEqAQABAAFAJiWgAnS6AfgAA7AA/vLrf/zYFc1z7/f/0uD9Lg/S4P/SkAAA',
  'base64',
);
// A genuine 1x1 AVIF (generated by sharp).
const TINY_AVIF = Buffer.from(
  'AAAAHGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZgAAAYRtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAAAAAAAA5waXRtAAAAAAABAAAANGlsb2MAAAAAREAAAgACAAAAAAGoAAEAAAAAAAAAEAABAAAAAAG4AAEAAAAAAAAAHQAAADhpaW5mAAAAAAACAAAAFWluZmUCAAAAAAEAAGF2MDEAAAAAFWluZmUCAAAAAAIAAGF2MDEAAAAAw2lwcnAAAACdaXBjbwAAABNjb2xybmNseAABAA0ABoAAAAAMYXYxQ4EAHAAAAAAUaXNwZQAAAAAAAAABAAAAAQAAAA5waXhpAAAAAAEIAAAAOGF1eEMAAAAAdXJuOm1wZWc6bXBlZ0I6Y2ljcDpzeXN0ZW1zOmF1eGlsaWFyeTphbHBoYQAAAAAMYXYxQ4EgAgAAAAAQcGl4aQAAAAADCAgIAAAAHmlwbWEAAAAAAAAAAgABBAGGAwcAAgSCAwSFAAAAGmlyZWYAAAAAAAAADmF1eGwAAgABAAEAAAA1bWRhdBIACgQYAAYVMgYYAAABQA8SAAoHOAAGEBDQaTIQGAAAAEAAsBNWZDGABE4fIA==',
  'base64',
);

const crc32 = (buf: Buffer): number => {
  let crc = 0xffffffff;
  for (const byte of buf) {
    crc ^= byte;
    for (let k = 0; k < 8; k++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
  }
  return (crc ^ 0xffffffff) >>> 0;
};

/** Builds a PNG header declaring `width`×`height` (fake, for bomb tests). */
const fakePngHeader = (width: number, height: number): Buffer => {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr.writeUInt8(8, 8); // bit depth
  ihdr.writeUInt8(2, 9); // color type (truecolor)
  const chunk = Buffer.concat([Buffer.from('IHDR'), ihdr]);
  const body = Buffer.concat([
    Buffer.from([0x00, 0x00, 0x00, 0x0d]),
    chunk,
    Buffer.from([crc32(chunk) >>> 24, (crc32(chunk) >> 16) & 0xff, (crc32(chunk) >> 8) & 0xff, crc32(chunk) & 0xff]),
  ]);
  return Buffer.concat([Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]), body]);
};

describe('detectFileType (magic bytes)', () => {
  it('detects PNG', () => {
    expect(detectFileType(TINY_PNG)).toBe('image/png');
  });
  it('detects JPEG', () => {
    expect(detectFileType(TINY_JPEG)).toBe('image/jpeg');
  });
  it('detects PDF', () => {
    expect(detectFileType(TINY_PDF)).toBe('application/pdf');
  });
  it('detects WebP', () => {
    expect(detectFileType(TINY_WEBP)).toBe('image/webp');
  });
  it('detects AVIF', () => {
    expect(detectFileType(TINY_AVIF)).toBe('image/avif');
  });
  it('does not mistake a HEIC/HEIF ftyp box for AVIF', () => {
    // `ftypheic` / `ftypmif1` majors must NOT be accepted as AVIF.
    const heic = Buffer.concat([
      Buffer.from([0x00, 0x00, 0x00, 0x1c]),
      Buffer.from('ftypheic', 'ascii'),
      Buffer.alloc(8, 0),
    ]);
    const mif1 = Buffer.concat([
      Buffer.from([0x00, 0x00, 0x00, 0x1c]),
      Buffer.from('ftypmif1', 'ascii'),
      Buffer.alloc(8, 0),
    ]);
    expect(detectFileType(heic)).toBeNull();
    expect(detectFileType(mif1)).toBeNull();
  });
  it('returns null for non-image/non-pdf content (a renamed script)', () => {
    expect(detectFileType(Buffer.from('#!/bin/sh\necho pwned\n'))).toBeNull();
  });
  it('returns null for a polyglot that does not start with an allowed signature', () => {
    expect(detectFileType(Buffer.from('<html><script>alert(1)</script></html>'))).toBeNull();
  });
});

describe('validateUploadContent', () => {
  it('accepts a genuine PNG with matching declared type', async () => {
    await expect(
      validateUploadContent({ buffer: TINY_PNG, declaredMimeType: 'image/png', originalName: 'card.png' }),
    ).resolves.toBeUndefined();
  });

  it('accepts a genuine WebP and AVIF with matching declared types', async () => {
    await expect(
      validateUploadContent({ buffer: TINY_WEBP, declaredMimeType: 'image/webp', originalName: 'card.webp' }),
    ).resolves.toBeUndefined();
    await expect(
      validateUploadContent({ buffer: TINY_AVIF, declaredMimeType: 'image/avif', originalName: 'card.avif' }),
    ).resolves.toBeUndefined();
  });

  it('rejects when declared MIME does not match actual content', async () => {
    await expect(
      validateUploadContent({ buffer: TINY_PNG, declaredMimeType: 'image/jpeg', originalName: 'card.jpg' }),
    ).rejects.toThrow(ValidationError);
  });

  it('rejects a disguised script with a .jpg name', async () => {
    await expect(
      validateUploadContent({ buffer: Buffer.from('#!/usr/bin/env node\nconsole.log(1)'), declaredMimeType: 'image/jpeg', originalName: 'evil.jpg' }),
    ).rejects.toThrow(/not recognized/);
  });

  it('rejects a PDF declared as an image', async () => {
    await expect(
      validateUploadContent({ buffer: TINY_PDF, declaredMimeType: 'image/png', originalName: 'x.pdf' }),
    ).rejects.toThrow(ValidationError);
  });

  it('rejects filenames containing CR/LF (header injection)', async () => {
    await expect(
      validateUploadContent({ buffer: TINY_PNG, declaredMimeType: 'image/png', originalName: 'bad\r\nContent-Type: x' }),
    ).rejects.toThrow(/filename/);
  });

  it('rejects an image header advertising absurd decoded dimensions (decompression bomb)', async () => {
    const bomb = fakePngHeader(20_000, 20_000);
    expect(bomb.length * (20_000 * 20_000)).toBeGreaterThan(MAX_DECODED_PIXELS);
    await expect(
      validateUploadContent({ buffer: bomb, declaredMimeType: 'image/png', originalName: 'bomb.png' }),
    ).rejects.toThrow(/too large|could not be read/);
  });
});
